# .github/dependabot.yml
version: 2
updates:
  # Maintain dependencies for the Node.js project
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday" # Optional: Pick a specific day
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "javascript"

  # Maintain GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
